version: '3.8'

services:
  app:
    image: laravel-build-test
    container_name: laravel_app_final
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx_final
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./dummies/:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db_final
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: user
    volumes:
      - dbdata_final:/var/lib/mysql
    networks:
      - laravel
    ports:
      - "3306:3306"

volumes:
  dbdata_final:

networks:
  laravel:
    driver: bridge
